### ISSUE TITLE
python27.dll could not be loaded

### ISSUE THREAD

**Issue by gellowmellow** [OpenTrading/OTMql4Py#7]
Hello,

I tried using this library. But when I try executing the script OTMql4PyTest.mq4 or running the EA OTPyTestNullEA.mq4, I get the error: python27.dll could not be loaded.

It's coming from the py27.dll but I can pinpoint further what's causing it. I can make sure that I have the python27.dll on my system32 folder but seems I cannot find these dlls pythoncom27.dll, pythoncomloader27.dll, pywintypes.dll.

Thanks!

**Comment by OpenTrading** [comment]
Thanks -  If you get a traceback message, could you cut and paste it into a comment on this 
Issue. We thought the code was written in a way that did not require pywin32, but it
in your setup it does.

The problem is that you don't have pywin32 inatalled into your Python:
install it from http://sourceforge.net/projects/pywin32/files/pywin32/
It's good software to have on Windows anyway.

We'll update the documentation to say it's a prerequisite.
Paste in a traceback with information on your OS, platform and version of Python,
and then let us know if installing pywin32 solved it for you.

**Comment by OpenTrading** [comment]
We've update the documentationto say pywin32 is a pre-requisite.
If you still have the problem with pywin32 installed, please reopen a new issue,
and give a traceback of the error as well as details on your versions of Python and Windows.
